### ISSUE TITLE
modloader doesnt display installed mods

### ISSUE THREAD

**Issue by GeraldTM** [J-Barta/reactor_modloader#1]
**Describe the bug**
modloader doesnt display installed mods

**To Reproduce**
install and open app
install mods

**Desktop (please complete the following information):**
 - Windows - v1.1

**Comment by J-Barta** [comment]
Everything is working on my installations (on both my machines). Could you open your mods directory (folder icon in the top right) and attach a screenshot of its contents? If there is an extracted folder there (there should be one for each mod you have installed), please attach at least one metadata.json file (should be in the extracted folder).

**Comment by GeraldTM** [comment]
fixed with a reinstall, though i had tried that before so idk what changed
